FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages

RUN corepack enable && corepack pnpm install --frozen-lockfile

CMD ["corepack", "pnpm", "dev"]
