apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canvas
resources:
  - namespace.yaml
  - backend-api-deployment.yaml
  - backend-worker-deployment.yaml
  - web-deployment.yaml
