apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas-web
  namespace: canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canvas-web
  template:
    metadata:
      labels:
        app: canvas-web
    spec:
      containers:
        - name: web
          image: canvas/web:dev
          imagePullPolicy: IfNotPresent
